<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Newsletter\Block\Subscribe $block */

?>
<div class="block newsletter" data-mage-init='{"autoModal": {}}' style="display: none;">
    <div class="title heading-4"><strong><?= $block->escapeHtml(__('Sign Up for Exclusive Offers:')) ?></strong></div>
    <div class="content">
        <?= $block->getChildHtml('block_newsletter' ) ?>
        <label class="label" for="newsletter"><?php /* @escapeNotVerified */ echo __('<span>your first order') ?></label>
        <form class="form subscribe"
            novalidate
            action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">
            <div class="field newsletter">
                <div class="control">

                    <input name="email" type="email" id="newsletter"
                           placeholder="<?= $block->escapeHtml(__('Email')) ?>"
                           data-mage-init='{"mage/trim-input":{}}'
                           data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </div>
            <div class="actions">
                <button class="action subscribe primary" title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>" type="submit" aria-label="Subscribe">
                    <span><?= $block->escapeHtml(__('Sign up for our newsletter')) ?></span>
                </button>
            </div>
        </form>
    </div>
</div>
